image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
  - build
#  - test
  - release

variables:
  MYGET_PACKAGE_URL: "https://www.myget.org/F/finitereality/api/v2/package"

build:
  stage: build
  script:
    - dotnet build Singyeong.Net.sln -c Release
    - dotnet pack Singyeong.Net.sln -c Release
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    expire_in: 1 week
    paths:
      - artifacts/pkg/Release/

# test:
#   stage: test
#   script:
#     - dotnet test Singyeong.Net.Tests.sln -c Release

push:
  stage: release
  only:
    - master@FiniteReality/Singyeong.Net
  dependencies:
    - build
  script:
    - for file in artifacts/pkg/Release/*; do
        dotnet nuget push $file -s "$MYGET_PACKAGE_URL" -k "$MYGET_API_KEY";
      done
